version: "2"
services:
  luckyframe:
    image: java:8
    container_name: "luckyframe"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6680:80"
      - "6633:6633"
    volumes:
      - "/home/operations/luckyframe/lib:/luckyFrame"
    entrypoint: sh /luckyFrame/start.sh
